### ISSUE TITLE
[ntfy] Default Authorization

### ISSUE THREAD

**Issue by Nollknolle** [ffflorian/node-packages#224]
Is it possible to set an default auth?
So i dont need to set the auth at every publish?

**Comment by ffflorian** [comment]
@Nollknolle Which package are you referring to?

**Comment by Nollknolle** [comment]
The ntfy package.

**Comment by ffflorian** [comment]
@Nollknolle thanks for the input, I'll add it as soon as I have the time for that :)

**Comment by ffflorian** [comment]
@Nollknolle this was fixed in `ntfy@1.5.0`.
