### ISSUE TITLE
@ffflorian/jszip-cli@3.5.2 no binary provided

### ISSUE THREAD

**Issue by greenhat616** [ffflorian/node-packages#327]
npx @ffflorian/jszip-cli@3.5.2
sh: 1: jszip-cli: not found

**Comment by ffflorian** [comment]
Hi @greenhat616, thanks for the report!

**Comment by ffflorian** [comment]
@greenhat616 This is fixed in [v3.5.6](https://www.npmjs.com/package/@ffflorian/jszip-cli/v/3.5.6).
