### ISSUE TITLE
Error: Can't resolve 'dgram'

### ISSUE THREAD

**Issue by PJMoraDev** [ffflorian/node-packages#543]
Hi @ffflorian 

I am trying to use your module but I get an error with one of its dependencies. This would be the error in console:

ERROR in ./node_modules/ntpclient/dist/esm/index.js 1:0-31
Module not found: Error: Can't resolve 'dgram' in 'path-to-my-project/node_modules/ntpclient/dist/esm'

**Comment by Adam014** [comment]
Yeah same issue, trying to get it running on Android app with React Native

**Comment by ffflorian** [comment]
This should be fixed with version `1.7.0`.
